### ISSUE TITLE
数据压缩率问题

### ISSUE THREAD

**Issue by nstl-zyb** [logpai/logzip#1]
在zip_out文件夹下生成的HDFS_2k.logzip.tar.bz2压缩文件，与直接采用tar -jcvf HDFS_2k.log.zip.bz2 HDFS_2k.log 生成的压缩文件，大小基本相同，甚至还大了一点

log_zip压缩大小
HDFS_2k.logzip.tar.bz2 ： 42747

直接压缩大小
HDFS_2k.log.zip.bz2 ： 42370

是我的理解出错了吗，还是说在out_zip下面并不是log_zip生成的压缩文件

期待您的回复！

**Comment by JinYang88** [comment]
您好！感谢关注我们的工作。

使用logzip压缩需要引入额外的空间存储额外的数据（比如模板的映射），因此在太小的log文件上（比如2k）使用可能压缩率提升效果不明显，请使用更大的log数据进行尝试。建议使用loghub中的全量HDFS数据。
