### ISSUE TITLE
How to decompress to the raw log?

### ISSUE THREAD

**Issue by liuruijin17** [logpai/logzip#2]
Hi, thanks for your great work!
I am wondering how I can decompress the generated `HDFS.logzip.tar.bz2` into the raw `HDFS.log`
I noticed your paper had mentioned how to decompress, but I did not find any codes about decompression.

**Comment by zxh-w** [comment]
I want to ask same question, Do you have any answer?

**Comment by JinYang88** [comment]
Thanks for your question! The primary goal of our paper is compressing to smaller size so we did not study too much about decompression. The following is a feasible way to do that:

HDFS.logzip.tar.bz2 can be first decompressed with standard bz2 tool. After that, you will find many small files within the produced folder after decompression. These files are in a readable csv format, which can be easily put back together to generate the original HDFS.log file.   

Thanks!
